#!/bin/bash

numb="$RANDOM"
START="1"
ext="ext"
counter="0"

ctrlc() {

  clear
  echo "you exit the game The number was $numb"
  START="0"
  sleep 5s
  exit

}

trap ctrlc INT

clear

echo ""
echo "Guess The Number Made by: AlphaDinosaur89"
echo ""
echo "To exit the game type ext or press ctrl+c"
echo ""

read -s -n 1 -p "Press any key to continue . . .";
echo "";

clear

SECONDS="0"

while (( $START == 1 )); do

  echo -n "put your guess now:"

  read guess

  if (( $guess == $numb )); then

    clear
    echo "You win! the number was $numb"
    counter=$((counter+1))
    START="0"
    echo "The number was $numb, you made $counter guess/guesses"
    printf "Elapsed time: %d days %02d:%02d:%02d.\n" $((SECONDS/(24*60*60))) $(((SECONDS/(60*60))%24)) $(((SECONDS/60)%60)) $((SECONDS%60)) 
    cd ..
    echo "The number was $numb, you made $counter guess/guesses" > lastwin.md
    printf "The number was $numb, you made $counter guess/guesses
Elapsed time: %d days %02d:%02d:%02d.\n" $((SECONDS/(24*60*60))) $(((SECONDS/(60*60))%24)) $(((SECONDS/60)%60)) $((SECONDS%60))  > lastwin.md
    sleep 5s
    exit

  fi 2> /dev/null

  if (( $guess > $numb )); then

    clear
    echo "The number is lower"
    counter=$((counter+1))
    echo "the last number was $guess"

  fi 2> /dev/null

  if (( $guess < $numb )); then

    clear
    echo "The number is higer"
    counter=$((counter+1))
    echo "the last number was $guess"

  fi 2> /dev/null

  if [[ $guess == $ext ]]; then

    clear
    echo "you exit the game The number was $numb"
    START="0"
    sleep 5s
    exit

  fi

done
